const PRODUCTS =[
    {
        id: 1,
        name: "Air Wing ",
        price: 599,
        image: "./images/shoes.jpg",
        category: "Shoe",
        amount: 1,
      },
      {
        id: 2,
        name: "All Model",
        author: "Nirala",
        price: 199,
        image: "./images/backCase.jpg",
        category: "accessories",
        amount: 1,
      },
      {
        id: 3,
        name: "Beats Gladiator",
        author: "Beats.co",
        price: 24999,
        image:"./images/beats.webp", 
        category: "Earphones",
        amount: 1,
      },
      {
        id: 4,
        name: "Veeba Clutch",
        author: "Veeba",
        price: 499,
        image:"./images/brown-clutch.jpg", 
        category: "Women Pouch",
        amount: 1,
      },
      {
        id: 5,
        name: "Iphone 14 256GB ",
        author: "Apple",
        price: 90999,
        image:"./images/iphone.webp",
        category: "Mobile",
        amount: 1,
      },
      {
        id: 6,
        name: "One Plus 10T",
        author: "By One Plus",
        price: 49499,
        image:"./images/onePlus.webp", 
        category: "Phone",
        amount: 1,
      },
      {
        id: 7,
        name: "Billion T-shirt ",
        author: "BIllion",
        price: 399,
        image:"./images/t-shirt.jpg",
        category: "Mens wear",
        amount: 1,
      },
      {
        id: 8,
        name: "Analog watches",
        author: "twilink",
        price: 889,
        image:"./images/watches.jpg",
        category: "Wall Watch", 
        amount: 1,
      }

];
export default PRODUCTS;